# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../interfaces/I_Busqueda.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from CatalogacionPatrones import Ui_Catalogaciondelpatron as cp
from ArbolPatrones import Ui_CatalogoPatron as ap


class Ui_BusquedaPatron(object):
    def setupUi(self, BusquedaPatron):
        BusquedaPatron.setObjectName("BusquedaPatron")
        BusquedaPatron.resize(414, 391)
        self.centralwidget = QtWidgets.QWidget(BusquedaPatron)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_datos = QtWidgets.QLineEdit(self.centralwidget)
        self.le_datos.setObjectName("le_datos")
        self.horizontalLayout.addWidget(self.le_datos)
        self.pb_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.pb_buscar.setText("")
        icon = QtGui.QIcon.fromTheme("system-search")
        self.pb_buscar.setIcon(icon)
        self.pb_buscar.setFlat(False)
        self.pb_buscar.setObjectName("pb_buscar")
        self.horizontalLayout.addWidget(self.pb_buscar)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_criterios = QtWidgets.QLabel(self.centralwidget)
        self.lb_criterios.setObjectName("lb_criterios")
        self.horizontalLayout_2.addWidget(self.lb_criterios)
        self.cb_nombre = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_nombre.setObjectName("cb_nombre")
        self.horizontalLayout_2.addWidget(self.cb_nombre)
        self.cb_roles = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_roles.setObjectName("cb_roles")
        self.horizontalLayout_2.addWidget(self.cb_roles)
        self.cb_dominio = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_dominio.setObjectName("cb_dominio")
        self.horizontalLayout_2.addWidget(self.cb_dominio)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tw_listaPatrones = QtWidgets.QTableWidget(self.centralwidget)
        self.tw_listaPatrones.setTabletTracking(False)
        self.tw_listaPatrones.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tw_listaPatrones.setAutoFillBackground(False)
        self.tw_listaPatrones.setFrameShape(QtWidgets.QFrame.Box)
        self.tw_listaPatrones.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tw_listaPatrones.setLineWidth(1)
        self.tw_listaPatrones.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tw_listaPatrones.setAutoScrollMargin(16)
        self.tw_listaPatrones.setShowGrid(True)
        self.tw_listaPatrones.setGridStyle(QtCore.Qt.DashDotLine)
        self.tw_listaPatrones.setWordWrap(True)
        self.tw_listaPatrones.setCornerButtonEnabled(True)
        self.tw_listaPatrones.setRowCount(0)
        self.tw_listaPatrones.setColumnCount(2)
        self.tw_listaPatrones.setObjectName("tw_listaPatrones")
        item = QtWidgets.QTableWidgetItem()
        self.tw_listaPatrones.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_listaPatrones.setHorizontalHeaderItem(1, item)
        self.tw_listaPatrones.horizontalHeader().setVisible(True)
        self.tw_listaPatrones.horizontalHeader().setCascadingSectionResizes(False)
        self.tw_listaPatrones.horizontalHeader().setDefaultSectionSize(200)
        self.tw_listaPatrones.horizontalHeader().setHighlightSections(False)
        self.tw_listaPatrones.horizontalHeader().setMinimumSectionSize(200)
        self.tw_listaPatrones.horizontalHeader().setSortIndicatorShown(False)
        self.tw_listaPatrones.horizontalHeader().setStretchLastSection(True)
        self.tw_listaPatrones.verticalHeader().setVisible(False)
        self.tw_listaPatrones.verticalHeader().setCascadingSectionResizes(False)
        self.tw_listaPatrones.verticalHeader().setDefaultSectionSize(0)
        self.tw_listaPatrones.verticalHeader().setHighlightSections(False)
        self.tw_listaPatrones.verticalHeader().setMinimumSectionSize(0)
        self.tw_listaPatrones.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tw_listaPatrones)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_verPatron = QtWidgets.QPushButton(self.centralwidget)
        self.pb_verPatron.setObjectName("pb_verPatron")
        self.horizontalLayout_3.addWidget(self.pb_verPatron)
        self.pb_crearPatron = QtWidgets.QPushButton(self.centralwidget)
        self.pb_crearPatron.setObjectName("pb_crearPatron")
        self.horizontalLayout_3.addWidget(self.pb_crearPatron)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        BusquedaPatron.setCentralWidget(self.centralwidget)
        
        self.pb_buscar.clicked.connect(self.buscar)
        self.pb_verPatron.clicked.connect(self.verPatron)
        self.pb_crearPatron.clicked.connect(self.crearPatron)

        self.retranslateUi(BusquedaPatron)
        QtCore.QMetaObject.connectSlotsByName(BusquedaPatron)

    def retranslateUi(self, BusquedaPatron):
        _translate = QtCore.QCoreApplication.translate
        BusquedaPatron.setWindowTitle(_translate("BusquedaPatron", "MainWindow"))
        self.le_datos.setPlaceholderText(_translate("BusquedaPatron", "Datos del patron"))
        self.lb_criterios.setText(_translate("BusquedaPatron", "Criterios de busqueda"))
        self.cb_nombre.setText(_translate("BusquedaPatron", "Nombre"))
        self.cb_roles.setText(_translate("BusquedaPatron", "Roles"))
        self.cb_dominio.setText(_translate("BusquedaPatron", "Dominio"))
        self.tw_listaPatrones.setSortingEnabled(False)
        item = self.tw_listaPatrones.horizontalHeaderItem(0)
        item.setText(_translate("BusquedaPatron", "Nombre"))
        item = self.tw_listaPatrones.horizontalHeaderItem(1)
        item.setText(_translate("BusquedaPatron", "Descripción"))
        self.pb_verPatron.setText(_translate("BusquedaPatron", "Ver Patron"))
        self.pb_crearPatron.setText(_translate("BusquedaPatron", "Crear Patron"))

    def crearPatron(self):
            self.nueva_ventana = QtWidgets.QMainWindow()
            self.ui_arbol_patrones = cp()
            self.ui_arbol_patrones.setupUi(self.nueva_ventana)
            BusquedaPatron.close()
            self.nueva_ventana.show()
            
            # Define a method to handle the close event and show the main window
            def on_close_event(event):
                BusquedaPatron.show()
                event.accept()

            # Connect the close event of the new window to the handler
            self.nueva_ventana.closeEvent = on_close_event
            
    def verPatron(self):
            self.nueva_ventana = QtWidgets.QMainWindow()
            self.ui_arbol_patrones = ap()
            self.ui_arbol_patrones.setupUi(self.nueva_ventana)
            BusquedaPatron.close()
            self.nueva_ventana.show()
            
            # Define a method to handle the close event and show the main window
            def on_close_event(event):
                BusquedaPatron.show()
                event.accept()

            # Connect the close event of the new window to the handler
            self.nueva_ventana.closeEvent = on_close_event
            
            
    def buscar(self):
        pass
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BusquedaPatron = QtWidgets.QMainWindow()
    ui = Ui_BusquedaPatron()
    ui.setupUi(BusquedaPatron)
    BusquedaPatron.show()
    sys.exit(app.exec_())
