# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../interfaces/Usos Conosidos.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import json
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UsosConocidos(object):
    def setupUi(self, UsosConocidos):
        UsosConocidos.setObjectName("UsosConocidos")
        UsosConocidos.resize(423, 338)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UsosConocidos.sizePolicy().hasHeightForWidth())
        UsosConocidos.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(UsosConocidos)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_usos = QtWidgets.QComboBox(UsosConocidos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_usos.sizePolicy().hasHeightForWidth())
        self.cb_usos.setSizePolicy(sizePolicy)
        self.cb_usos.setEditable(True)
        self.cb_usos.setDuplicatesEnabled(False)
        self.cb_usos.setFrame(True)
        self.cb_usos.setObjectName("cb_usos")
        self.horizontalLayout_2.addWidget(self.cb_usos)
        self.pb_adicionar = QtWidgets.QPushButton(UsosConocidos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_adicionar.sizePolicy().hasHeightForWidth())
        self.pb_adicionar.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pb_adicionar.setIcon(icon)
        self.pb_adicionar.setObjectName("pb_adicionar")
        self.horizontalLayout_2.addWidget(self.pb_adicionar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.lb_usosConocidos = QtWidgets.QLabel(UsosConocidos)
        self.lb_usosConocidos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_usosConocidos.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_usosConocidos.setTextFormat(QtCore.Qt.PlainText)
        self.lb_usosConocidos.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_usosConocidos.setWordWrap(False)
        self.lb_usosConocidos.setObjectName("lb_usosConocidos")
        self.verticalLayout_2.addWidget(self.lb_usosConocidos)
        self.lw_usos = QtWidgets.QListWidget(UsosConocidos)
        self.lw_usos.setObjectName("lw_usos")
        self.verticalLayout_2.addWidget(self.lw_usos)
        self.pb_eliminar = QtWidgets.QPushButton(UsosConocidos)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pb_eliminar.setIcon(icon)
        self.pb_eliminar.setObjectName("pb_eliminar")
        self.verticalLayout_2.addWidget(self.pb_eliminar)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(UsosConocidos)
        icon = QtGui.QIcon.fromTheme("window-close")
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(UsosConocidos)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.optenerRuta()
        self.listarUsos()
        self.pb_adicionar.clicked.connect(self.adicionar)
        self.pb_eliminar.clicked.connect(self.eliminar)
        self.pushButton.clicked.connect(UsosConocidos.close)
        self.pushButton_2.clicked.connect(self.guardar)
        
        self.retranslateUi(UsosConocidos)
        QtCore.QMetaObject.connectSlotsByName(UsosConocidos)
        
    def optenerRuta(self):
        with open("conf.json", "r") as file:
            data = json.load(file)
            self.file = data["repositorio"]
            
    def listarUsos(self):
        self.lw_usos.clear()
        with open(f"{self.file}/UsosConocidos.json", "r") as file:
            data = json.load(file)
            self.cb_usos.addItem("Nuevo Uso")
            for uso,_ in data["Usos"].items():
                self.cb_usos.addItem(uso)
            
    def adicionar(self):
        uso = self.cb_usos.currentText()
        if uso:
            self.lw_usos.addItem(uso)
            
    def eliminar(self):
        for item in self.lw_usos.selectedItems():
            self.lw_usos.takeItem(self.lw_usos.row(item))
            
    def guardar(self):
        #optener todos los usos de la lista lw_usos
        usos = []
        for i in range(self.lw_usos.count()):
            usos.append(self.lw_usos.item(i).text())
        with open("data.json", "r") as file:
            data = json.load(file)
            data["Usos"] = usos
        with open("data.json", "w") as file:
            json.dump(data, file)
        self.lw_usos.clear()
        self.cb_usos.clear()
        self.listarUsos()
        
    def retranslateUi(self, UsosConocidos):
        _translate = QtCore.QCoreApplication.translate
        UsosConocidos.setWindowTitle(_translate("UsosConocidos", "Usos Conocidos del Patron de Analisis"))
        self.cb_usos.setCurrentText(_translate("UsosConocidos", "Nuevo uso"))
        self.cb_usos.setPlaceholderText(_translate("UsosConocidos", "Nuevo uso"))
        self.pb_adicionar.setText(_translate("UsosConocidos", "Adicionar"))
        self.lb_usosConocidos.setText(_translate("UsosConocidos", "Usos conocidos "))
        self.pb_eliminar.setText(_translate("UsosConocidos", "Eliminar"))
        self.pushButton.setText(_translate("UsosConocidos", "Cancelar"))
        self.pushButton_2.setText(_translate("UsosConocidos", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UsosConocidos = QtWidgets.QDialog()
    ui = Ui_UsosConocidos()
    ui.setupUi(UsosConocidos)
    UsosConocidos.show()
    sys.exit(app.exec_())
