# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../interfaces/Usos Conosidos.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UsosConocidos(object):
    def setupUi(self, UsosConocidos):
        UsosConocidos.setObjectName("UsosConocidos")
        UsosConocidos.resize(423, 338)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UsosConocidos.sizePolicy().hasHeightForWidth())
        UsosConocidos.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(UsosConocidos)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_usos = QtWidgets.QComboBox(UsosConocidos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_usos.sizePolicy().hasHeightForWidth())
        self.cb_usos.setSizePolicy(sizePolicy)
        self.cb_usos.setEditable(True)
        self.cb_usos.setDuplicatesEnabled(False)
        self.cb_usos.setFrame(True)
        self.cb_usos.setObjectName("cb_usos")
        self.horizontalLayout_2.addWidget(self.cb_usos)
        self.cb_categoria = QtWidgets.QComboBox(UsosConocidos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_categoria.sizePolicy().hasHeightForWidth())
        self.cb_categoria.setSizePolicy(sizePolicy)
        self.cb_categoria.setEditable(True)
        self.cb_categoria.setObjectName("cb_categoria")
        self.horizontalLayout_2.addWidget(self.cb_categoria)
        self.pb_adicionar = QtWidgets.QPushButton(UsosConocidos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_adicionar.sizePolicy().hasHeightForWidth())
        self.pb_adicionar.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pb_adicionar.setIcon(icon)
        self.pb_adicionar.setObjectName("pb_adicionar")
        self.horizontalLayout_2.addWidget(self.pb_adicionar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.lb_usosConocidos = QtWidgets.QLabel(UsosConocidos)
        self.lb_usosConocidos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_usosConocidos.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_usosConocidos.setTextFormat(QtCore.Qt.PlainText)
        self.lb_usosConocidos.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_usosConocidos.setWordWrap(False)
        self.lb_usosConocidos.setObjectName("lb_usosConocidos")
        self.verticalLayout_2.addWidget(self.lb_usosConocidos)
        self.lw_usos = QtWidgets.QListWidget(UsosConocidos)
        self.lw_usos.setObjectName("lw_usos")
        self.verticalLayout_2.addWidget(self.lw_usos)
        self.pb_eliminar = QtWidgets.QPushButton(UsosConocidos)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pb_eliminar.setIcon(icon)
        self.pb_eliminar.setObjectName("pb_eliminar")
        self.verticalLayout_2.addWidget(self.pb_eliminar)

        self.retranslateUi(UsosConocidos)
        QtCore.QMetaObject.connectSlotsByName(UsosConocidos)

    def retranslateUi(self, UsosConocidos):
        _translate = QtCore.QCoreApplication.translate
        UsosConocidos.setWindowTitle(_translate("UsosConocidos", "Usos Conocidos del Patron de Analisis"))
        self.cb_usos.setCurrentText(_translate("UsosConocidos", "Nuevo uso"))
        self.cb_usos.setPlaceholderText(_translate("UsosConocidos", "Nuevo uso"))
        self.cb_categoria.setCurrentText(_translate("UsosConocidos", "Nueva categoria"))
        self.pb_adicionar.setText(_translate("UsosConocidos", "Adicionar"))
        self.lb_usosConocidos.setText(_translate("UsosConocidos", "Usos conocidos "))
        self.pb_eliminar.setText(_translate("UsosConocidos", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UsosConocidos = QtWidgets.QDialog()
    ui = Ui_UsosConocidos()
    ui.setupUi(UsosConocidos)
    UsosConocidos.show()
    sys.exit(app.exec_())
