# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../interfaces/Vista Previa del patron.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VistaPrevia(object):
    def setupUi(self, VistaPrevia):
        VistaPrevia.setObjectName("VistaPrevia")
        VistaPrevia.resize(768, 517)
        self.centralwidget = QtWidgets.QWidget(VistaPrevia)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_template = QtWidgets.QLabel(self.tab)
        self.lb_template.setText("")
        self.lb_template.setObjectName("lb_template")
        self.horizontalLayout_2.addWidget(self.lb_template)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_vistaAlcance = QtWidgets.QLabel(self.tab_2)
        self.lb_vistaAlcance.setText("")
        self.lb_vistaAlcance.setObjectName("lb_vistaAlcance")
        self.horizontalLayout_3.addWidget(self.lb_vistaAlcance)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_vistaEstructura = QtWidgets.QLabel(self.tab_3)
        self.lb_vistaEstructura.setText("")
        self.lb_vistaEstructura.setObjectName("lb_vistaEstructura")
        self.horizontalLayout_4.addWidget(self.lb_vistaEstructura)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lb_vistaComportamiento = QtWidgets.QLabel(self.tab_4)
        self.lb_vistaComportamiento.setText("")
        self.lb_vistaComportamiento.setObjectName("lb_vistaComportamiento")
        self.horizontalLayout_5.addWidget(self.lb_vistaComportamiento)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.pb_aceptar.setObjectName("pb_aceptar")
        self.horizontalLayout.addWidget(self.pb_aceptar)
        self.pb_instaciarPatron = QtWidgets.QPushButton(self.centralwidget)
        self.pb_instaciarPatron.setObjectName("pb_instaciarPatron")
        self.horizontalLayout.addWidget(self.pb_instaciarPatron)
        self.verticalLayout.addLayout(self.horizontalLayout)
        VistaPrevia.setCentralWidget(self.centralwidget)

        self.retranslateUi(VistaPrevia)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(VistaPrevia)

    def retranslateUi(self, VistaPrevia):
        _translate = QtCore.QCoreApplication.translate
        VistaPrevia.setWindowTitle(_translate("VistaPrevia", "Vista Previa del patron"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("VistaPrevia", "Template"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("VistaPrevia", "Vista de Alcance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("VistaPrevia", "Vista de Estructura"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("VistaPrevia", "Vista de Comportamiento"))
        self.pb_aceptar.setText(_translate("VistaPrevia", "Aceptar"))
        self.pb_instaciarPatron.setText(_translate("VistaPrevia", "Instanciar Patron"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VistaPrevia = QtWidgets.QMainWindow()
    ui = Ui_VistaPrevia()
    ui.setupUi(VistaPrevia)
    VistaPrevia.show()
    sys.exit(app.exec_())
