# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/Nuevo dominio.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewDomain(object):
    def setupUi(self, NewDomain):
        NewDomain.setObjectName("NewDomain")
        NewDomain.resize(488, 428)
        NewDomain.setMaximumSize(QtCore.QSize(900, 700))
        self.verticalLayout = QtWidgets.QVBoxLayout(NewDomain)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_nuevoDominio = QtWidgets.QLabel(NewDomain)
        self.lb_nuevoDominio.setObjectName("lb_nuevoDominio")
        self.horizontalLayout_3.addWidget(self.lb_nuevoDominio)
        self.le_nameDomain = QtWidgets.QLineEdit(NewDomain)
        self.le_nameDomain.setObjectName("le_nameDomain")
        self.horizontalLayout_3.addWidget(self.le_nameDomain)
        self.cb_domains = QtWidgets.QComboBox(NewDomain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_domains.sizePolicy().hasHeightForWidth())
        self.cb_domains.setSizePolicy(sizePolicy)
        self.cb_domains.setEditable(True)
        self.cb_domains.setCurrentText("")
        self.cb_domains.setDuplicatesEnabled(False)
        self.cb_domains.setFrame(True)
        self.cb_domains.setObjectName("cb_domains")
        self.horizontalLayout_3.addWidget(self.cb_domains)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.lb_requisitos = QtWidgets.QLabel(NewDomain)
        self.lb_requisitos.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_requisitos.setObjectName("lb_requisitos")
        self.verticalLayout.addWidget(self.lb_requisitos)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_requirements = QtWidgets.QComboBox(NewDomain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_requirements.sizePolicy().hasHeightForWidth())
        self.cb_requirements.setSizePolicy(sizePolicy)
        self.cb_requirements.setEditable(True)
        self.cb_requirements.setDuplicatesEnabled(False)
        self.cb_requirements.setFrame(True)
        self.cb_requirements.setObjectName("cb_requirements")
        self.horizontalLayout.addWidget(self.cb_requirements)
        self.pb_add = QtWidgets.QPushButton(NewDomain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_add.sizePolicy().hasHeightForWidth())
        self.pb_add.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pb_add.setIcon(icon)
        self.pb_add.setObjectName("pb_add")
        self.horizontalLayout.addWidget(self.pb_add)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lw_requirements = QtWidgets.QListWidget(NewDomain)
        self.lw_requirements.setEnabled(True)
        self.lw_requirements.setObjectName("lw_requirements")
        self.verticalLayout.addWidget(self.lw_requirements)
        self.pb_deleteRequirements = QtWidgets.QPushButton(NewDomain)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pb_deleteRequirements.setIcon(icon)
        self.pb_deleteRequirements.setObjectName("pb_deleteRequirements")
        self.verticalLayout.addWidget(self.pb_deleteRequirements)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_cancel = QtWidgets.QPushButton(NewDomain)
        icon = QtGui.QIcon.fromTheme("window-close")
        self.pb_cancel.setIcon(icon)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_2.addWidget(self.pb_cancel)
        self.pb_save = QtWidgets.QPushButton(NewDomain)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.pb_save.setIcon(icon)
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout_2.addWidget(self.pb_save)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(NewDomain)
        QtCore.QMetaObject.connectSlotsByName(NewDomain)
        
        

    def retranslateUi(self, NewDomain):
        _translate = QtCore.QCoreApplication.translate
        NewDomain.setWindowTitle(_translate("NewDomain", "Dialog"))
        self.lb_nuevoDominio.setText(_translate("NewDomain", "Nombre Dominio"))
        self.cb_domains.setPlaceholderText(_translate("NewDomain", "Nuevo requisito"))
        self.lb_requisitos.setText(_translate("NewDomain", "Requisitos"))
        self.cb_requirements.setCurrentText(_translate("NewDomain", "Nuevo Requisito"))
        self.cb_requirements.setPlaceholderText(_translate("NewDomain", "Nuevo requisito"))
        self.pb_add.setText(_translate("NewDomain", "Adicionar"))
        self.pb_deleteRequirements.setText(_translate("NewDomain", "Eliminar Requisito"))
        self.pb_cancel.setText(_translate("NewDomain", "Cancelar"))
        self.pb_save.setText(_translate("NewDomain", "Guardar"))
