# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/Vista Patrones.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets
from ui_generated.ui_frameDatosInstanciacion import Instanciacion
from logic.pattern_repository import PatternRepository

class Ui_instantiateWindow(object):
    def __init__(self, images, parent=None):
        self.images = images
        self.parent = parent
        self.patternRepository = PatternRepository()
        self.images_path = self.patternRepository.get_path_images_by_name(self.parent)
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(891, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.tw_preview = QtWidgets.QTabWidget(self.centralwidget)
        self.tw_preview.setObjectName("tw_preview")
        self.template_2 = QtWidgets.QWidget()
        self.template_2.setObjectName("template_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.template_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.template_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 513, 495))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lb_template = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_template.sizePolicy().hasHeightForWidth())
        self.lb_template.setSizePolicy(sizePolicy)
        self.lb_template.setText("")
        self.lb_template.setObjectName("lb_template")
        self.verticalLayout_10.addWidget(self.lb_template)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.tw_preview.addTab(self.template_2, "")
        self.scope = QtWidgets.QWidget()
        self.scope.setObjectName("scope")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scope)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.scope)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 513, 495))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lb_scope = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lb_scope.setText("")
        self.lb_scope.setObjectName("lb_scope")
        self.verticalLayout_7.addWidget(self.lb_scope)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.addWidget(self.scrollArea_3)
        self.tw_preview.addTab(self.scope, "")
        self.structure = QtWidgets.QWidget()
        self.structure.setObjectName("structure")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.structure)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.structure)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 513, 495))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lb_structure = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_structure.sizePolicy().hasHeightForWidth())
        self.lb_structure.setSizePolicy(sizePolicy)
        self.lb_structure.setText("")
        self.lb_structure.setObjectName("lb_structure")
        self.verticalLayout_9.addWidget(self.lb_structure)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.tw_preview.addTab(self.structure, "")
        self.behavior = QtWidgets.QWidget()
        self.behavior.setObjectName("behavior")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.behavior)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.behavior)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 513, 495))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lb_behavior = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.lb_behavior.setText("")
        self.lb_behavior.setObjectName("lb_behavior")
        self.verticalLayout_8.addWidget(self.lb_behavior)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_6.addWidget(self.scrollArea_4)
        self.tw_preview.addTab(self.behavior, "")
        self.verticalLayout_2.addWidget(self.tw_preview)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_2.sizePolicy().hasHeightForWidth())
        self.dockWidget_2.setSizePolicy(sizePolicy)
        self.dockWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockWidget_2.setStyleSheet("")
        self.dockWidget_2.setFloating(False)
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sa_datos = QtWidgets.QScrollArea(self.dockWidgetContents_2)
        self.sa_datos.setStyleSheet("")
        self.sa_datos.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sa_datos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sa_datos.setWidgetResizable(True)
        self.sa_datos.setObjectName("sa_datos")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 306, 556))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_data = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame_data.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_data.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_data.setObjectName("frame_data")
        self.verticalLayout_11.addWidget(self.frame_data)
        self.pb_instantiate = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_instantiate.sizePolicy().hasHeightForWidth())
        self.pb_instantiate.setSizePolicy(sizePolicy)
        self.pb_instantiate.setObjectName("pb_instantiate")
        self.verticalLayout_11.addWidget(self.pb_instantiate)
        self.sa_datos.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout.addWidget(self.sa_datos)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_2)

        self.retranslateUi(MainWindow)
        self.tw_preview.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #=======================================================================
        self.set_image(self.lb_template, self.images['template'], "Error al cargar la imagen")
        self.set_image(self.lb_scope, self.images['scopeModel'], "Error al cargar la imagen")
        self.set_image(self.lb_structure, self.images['structureModel'], "Error al cargar la imagen")
        self.set_image(self.lb_behavior, self.images['behaviorModel'], "Error al cargar la imagen")
        
        self.tw_preview.currentChanged.connect(lambda index: self.change_data(self.images_path))

        
        #=======================================================================
    def change_data(self, images):
        print("Cambio de pestaña")
        print(images)

        svg_content = None
        
        # Determina qué contenido SVG mostrar basado en la pestaña activa
        current_index = self.tw_preview.currentIndex()
        
        if current_index == 0:  # Template tab
            svg_content = images['template']
            print("Template")
        elif current_index == 1:  # Scope tab
            svg_content = images['scopeModel']
            print("Alcance")
        elif current_index == 2:  # Structure tab
            svg_content = images['structureModel']
            print("Estructura")
        elif current_index == 3:  # Behavior tab
            svg_content = images['behaviorModel']
            print("Comportamiento")
        
        # Verifica si el contenido SVG es válido
        if not svg_content or not os.path.exists(svg_content):
            print("Error al cargar el archivo")
            return

        # Carga el contenido del SVG
        svg_content = self.load_svg_from_file(svg_content)
        
        # Instancia la clase Instanciacion con el nuevo contenido
        new_frame_data = Instanciacion(svg_content)
        
        # Actualiza el layout del QDockWidget
        if self.dockWidget_2:
            dock_widget_layout = self.dockWidget_2.widget().layout()
            
            if dock_widget_layout:
                # Limpia el layout actual
                while dock_widget_layout.count():
                    item = dock_widget_layout.takeAt(0)
                    if item.widget():
                        item.widget().deleteLater()
                
                # Agrega el nuevo frame_data al layout
                dock_widget_layout.addWidget(new_frame_data)
            else:
                print("No se encontró el layout en dockWidget_2")
        
        # Forzar la actualización del UI
        QtWidgets.QApplication.processEvents()
        
    def load_svg_from_file(self, file_path):
        # Open the SVG file and read its content.
        with open(file_path, 'r', encoding='utf-8') as file:
            return file.read()
        
    def set_image(self,label, image_path, error_message):
        #verificar si la imagen es null o vacio
        if image_path:
            label.setPixmap(image_path)
        else:
            label.setText(error_message)
            

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Modelos"))
        self.tw_preview.setTabText(self.tw_preview.indexOf(self.template_2), _translate("MainWindow", "Template"))
        self.tw_preview.setTabText(self.tw_preview.indexOf(self.scope), _translate("MainWindow", "Vista de Alcance"))
        self.tw_preview.setTabText(self.tw_preview.indexOf(self.structure), _translate("MainWindow", "Vista de Estructura"))
        self.tw_preview.setTabText(self.tw_preview.indexOf(self.behavior), _translate("MainWindow", "Vista de Comportamiento"))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "Instanciar"))
        self.pb_instantiate.setText(_translate("MainWindow", "Instanciar"))
