# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/Usos Conosidos.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from logic.pattern_repository import PatternRepository
from ui_generated.ui_customInputDialog import CustomInputDialog
from ui_generated.ui_messageBoxManager import MessageBoxManager


class Ui_KnowUses(object):
    def setupUi(self, KnowUses):
        KnowUses.setObjectName("KnowUses")
        KnowUses.resize(423, 338)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(KnowUses.sizePolicy().hasHeightForWidth())
        KnowUses.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(KnowUses)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_uses = QtWidgets.QComboBox(KnowUses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_uses.sizePolicy().hasHeightForWidth())
        self.cb_uses.setSizePolicy(sizePolicy)
        self.cb_uses.setEditable(True)
        self.cb_uses.setDuplicatesEnabled(False)
        self.cb_uses.setFrame(True)
        self.cb_uses.setObjectName("cb_uses")
        self.horizontalLayout_2.addWidget(self.cb_uses)
        self.pb_addUse = QtWidgets.QPushButton(KnowUses)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_addUse.sizePolicy().hasHeightForWidth())
        self.pb_addUse.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pb_addUse.setIcon(icon)
        self.pb_addUse.setObjectName("pb_addUse")
        self.horizontalLayout_2.addWidget(self.pb_addUse)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.lb_usosConocidos = QtWidgets.QLabel(KnowUses)
        self.lb_usosConocidos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_usosConocidos.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_usosConocidos.setTextFormat(QtCore.Qt.PlainText)
        self.lb_usosConocidos.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_usosConocidos.setWordWrap(False)
        self.lb_usosConocidos.setObjectName("lb_usosConocidos")
        self.verticalLayout_2.addWidget(self.lb_usosConocidos)
        self.lw_uses = QtWidgets.QListWidget(KnowUses)
        self.lw_uses.setObjectName("lw_uses")
        self.verticalLayout_2.addWidget(self.lw_uses)
        self.pb_removeUse = QtWidgets.QPushButton(KnowUses)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pb_removeUse.setIcon(icon)
        self.pb_removeUse.setObjectName("pb_removeUse")
        self.verticalLayout_2.addWidget(self.pb_removeUse)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_cancel = QtWidgets.QPushButton(KnowUses)
        icon = QtGui.QIcon.fromTheme("window-close")
        self.pb_cancel.setIcon(icon)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_3.addWidget(self.pb_cancel)
        self.pb_save = QtWidgets.QPushButton(KnowUses)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.pb_save.setIcon(icon)
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout_3.addWidget(self.pb_save)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(KnowUses)
        QtCore.QMetaObject.connectSlotsByName(KnowUses)
        #================================================================
        self.KnowUses = KnowUses
        self.patternRepository = PatternRepository()
        self.menssageManager = MessageBoxManager()
        self.listUses()
        self.pb_addUse.clicked.connect(self.addUse)
        self.pb_removeUse.clicked.connect(self.removeUse)
        self.pb_cancel.clicked.connect(KnowUses.close)
        self.pb_save.clicked.connect(self.save)
        
    def setUses(self,uses):
        if uses:
            for use in uses:
                self.lw_uses.addItem(use)
                
    def getUses(self):
        uses = []
        for i in range(self.lw_uses.count()):
            uses.append(self.lw_uses.item(i).text())
        return uses
            
    def save(self):
        uses = []
        for i in range(self.lw_uses.count()):
            uses.append(self.lw_uses.item(i).text())
            
        if self.valid():
            self.KnowUses.accept()
        
    def valid(self):
        if self.lw_uses.count() == 0:
            #QtWidgets.QMessageBox.critical(self.KnowUses, 'Error', 'Debe ingresar al menos un uso')
            self.lw_uses.setStyleSheet("border: 1px solid red;")
            self.menssageManager.show_critical_message(self.KnowUses, 'Error', 'Debe ingresar al menos un uso')
            return False
        return True
    
    def listUses(self):
        uses = self.patternRepository.get_knowUses()
        for use in uses["Uses"].keys():
                self.cb_uses.addItem(use)
            
        
    def addUse(self):
        for i in range(self.lw_uses.count()):
            if self.cb_uses.currentText() == self.lw_uses.item(i).text():
                self.menssageManager.show_info_message(self.KnowUses, 'Info', 'El uso ya se encuentra en la lista')
                return
        self.lw_uses.addItem(self.cb_uses.currentText())

    def removeUse(self):
        self.lw_uses.takeItem(self.lw_uses.currentRow())
        

    def retranslateUi(self, KnowUses):
        _translate = QtCore.QCoreApplication.translate
        KnowUses.setWindowTitle(_translate("KnowUses", "Usos Conocidos del Patron de Analisis"))
        self.cb_uses.setCurrentText(_translate("KnowUses", "Nuevo uso"))
        self.cb_uses.setPlaceholderText(_translate("KnowUses", "Nuevo uso"))
        self.pb_addUse.setText(_translate("KnowUses", "Adicionar"))
        self.lb_usosConocidos.setText(_translate("KnowUses", "Usos conocidos "))
        self.pb_removeUse.setText(_translate("KnowUses", "Eliminar"))
        self.pb_cancel.setText(_translate("KnowUses", "Cancelar"))
        self.pb_save.setText(_translate("KnowUses", "Guardar"))
